name: 'ml_sample'
type: 'project'
rootdir: ''
children:
    - name: '.gitignore'
      type: 'file'
    - name: 'docs'
      type: 'directory'
      children:
        - name: 'summary.md'
          type: 'file'
