body:
  name: 'ml_sample'
  type: 'project'
  rootdir: ''
  virtualenv: false
  children:
    - name: '.gitignore'
      type: 'file'
    - name: 'README.md'
      type: 'file'
    - name: 'requirements.txt'
      type: 'file'
    - name: 'Dockerfile'
      type: 'file'
    - name: 'modules'
      type: 'directory'
      children:
        - name: '.gitkeep'
          type: 'file'
    - name: 'workspace'
      type: 'directory'
      children:
        - name: '.gitkeep'
          type: 'file'

meta:
  jupyter:
    install: true
    config_location: 'default'
