body:
  name: 'ml_sample'
  type: 'project'
  rootdir: ''
  virtualenv: false
  children:
    - name: '.gitignore'
      type: 'file'
    - name: 'docs'
      type: 'directory'
      children:
        - name: 'summary.md'
          type: 'file'

meta:
  jupyter: true
